### ISSUE TITLE
LCStdhepRdr has a serious resource leak

### ISSUE THREAD

**Issue by jstrube** [iLCSoft/LCIO#1]
The LCStdhepRdr returns a new MCParticle collection, which is never deleted.
Could this be changed to be handled symmetrically to reading a collection from the lcio reader, which does not need to be treated in a special way?

My use case is to run over a large number of stdhep files, and it's currently easier to just run stdhepjob before opening the file. Running over all stdhep files in one job is not possible due to the mem leak in the stdhep reader.

**Comment by gaede** [comment]
I don't think there is any leak in LCStdhepRdr. LCStdHepRdr::readEvent() returns a new collection with MCParticles and it is the users responsibility to delete it when it is no longer used. This is the normal behavior in LCIO. Note that typically collections are added to an event and then only the event needs to be deleted...

**Comment by jstrube** [comment]
Let me phrase this in a different way: 
My understanding is the following:
If I run `LCStdHepRdr::readEvent()` 1000 times, I have 1000 objects in memory.
If I run `LCReader::readNextEvent()` 1000 times, I only have a single object in memory.
Are you saying this is not the case?

I would like to have a function `LCStdHepRdr::readNextEvent()` that I can run 1000 times and I only have a single object in memory.

**Comment by gaede** [comment]
There is a fundamental difference between the two: `LCStdHepRdr::readEvent()` reads an stdhep file and ceates a new MCParticle collection for the user, whereas `LCReader::readNextEvent()` reads the next LCEvent from an LCIO file. In contrast to the latter, we do not know what the user is going to do with the collection in the first case and thus cannot handle the memory. This is also why the method is `deprecated` and one should use ` updateNextEvent()` instead. 
Please note that also here you are responsible for deleting the LCEvent, following the general principle: if you created it, you need to delete it. This can be easily done using a unique_ptr:
```c++
 std::unique_ptr<LCEventImpl> evt( new LCEventImpl ) ;
 // read the next stdhep event and add an MCParticle collection to the event
 rdr.updateNextEvent( evt.get() ) ;
```

**Comment by jstrube** [comment]
I find the argument about the asymmetry unconvincing. This is exposing the user to an implementation detail.
Anyway deprecating this thing is definitely the right step, and thank you for the LCEvent example. I will use that in my bindings.
