### ISSUE TITLE
Failure to build 2.15 at DESY

### ISSUE THREAD

**Issue by jstrube** [iLCSoft/LCIO#105]
I'm trying to build the latest version of LCIO at the NAF, but it fails due to some linker issues.

 - OS version: CENTOS7 (DESY NAF)
 - Compiler version: e.g GCC 8.2.0
 - Package version: 2.15.01
 - Reproduced by: exact steps to reproduce the problem:
```
source /cvmfs/belle.cern.ch/tools/b2setup release-04-02-08
wget https://github.com/iLCSoft/LCIO/archive/v02-15-01.tar.gz
tar xzf v02-15-01.tar.gz
cd LCIO-02-15-01
mkdir build
cd build
export CXX=/cvmfs/belle.cern.ch/el7/externals/v01-08-00/Linux_x86_64/common/bin/gcc
export CC=/cvmfs/belle.cern.ch/el7/externals/v01-08-00/Linux_x86_64/common/bin/gcc
cmake -DBUILD_ROOTDICT=ON -DCMAKE_CXX_STANDARD=17  ..
make >& build.log
```
 - Input: 
[cmake.log](https://github.com/iLCSoft/LCIO/files/5081454/cmake.log)
[build.log](https://github.com/iLCSoft/LCIO/files/5081455/build.log)

**Comment by rete** [comment]
```
export CXX=/cvmfs/belle.cern.ch/el7/externals/v01-08-00/Linux_x86_64/common/bin/gcc
```
is this intentional? Shouldn't it be:

```
export CXX=/cvmfs/belle.cern.ch/el7/externals/v01-08-00/Linux_x86_64/common/bin/g++
```

**Comment by jstrube** [comment]
You're right, it should. Does that fix the issue?

**Comment by rete** [comment]
I have not tested, I just noticed it while glancing at your description. Can you give it a try?

**Comment by jstrube** [comment]
That seems to work with LCIO-02-15-02!
