### ISSUE TITLE
Python bindings work only with sources present.

### ISSUE THREAD

**Issue by vvolkl** [iLCSoft/LCIO#106]
When building LCIO and removing the sources, all python imports fail with many error messages of the type:

```
Error in <TClass::LoadClassInfo>: no interpreter information for class IMPL::TrackImpl is available even though it has a TClass initialization routine.
IMPL dictionary payload:5:10: fatal error: 'include/IMPL/AccessChecked.h' file not found
#include "include/IMPL/AccessChecked.h"
```

This is a bit reminiscent of https://github.com/AIDASoft/DD4hep/issues/565. @andresailer, maybe your fix works here as well?

**Comment by andresailer** [comment]
The fix there was to have all the files available.

**Comment by rete** [comment]
@andresailer @vvolkl Is this fixed by now?

**Comment by tmadlener** [comment]
Potentially related: #136

**Comment by tmadlener** [comment]
This still seems to be an issue if one actually tries to use the python bindings

```python
from pyLCIO import IOIMPL

reader = IOIMPL.LCFactory.getInstance().createLCReader()
```

fails with the following error
```console
In file included from IOIMPL dictionary payload:9:
/cvmfs/sw.hsf.org/spackages/linux-centos7-x86_64/gcc-8.3.0/lcio-2.16.1-nqt55lk5fmwwer334skcjgjcihnbghmr/include/IOIMPL/LCEventLazyImpl.h:6:10: fatal error: 'SIO/SIOHandlerMgr.h' file not found
#include "SIO/SIOHandlerMgr.h"
         ^~~~~~~~~~~~~~~~~~~~~
Error in <TInterpreter::AutoParse>: Error parsing payload code for class IOIMPL::LCFactory with content:

[...]
```

This only seems to happen with out of source installations (i.e. spack). Installations with iLCSoft do not have this problem, although the `<install-prefix>/include/SIO` directory is empty in both cases.

**Comment by tmadlener** [comment]
I have checked that this also happens without spack and it does. The two headers: `SIOHandlerMgr.h` and `SIOObjectHandler.h` need to be present in `<install-prefix>/include/SIO` for the above example to work.

Should we try and fix these installation issues in LCIO rather than in the spack recipe for LCIO?
