### ISSUE TITLE
[Request] Add StatusQuality bitfield to SimTrackerHit

### ISSUE THREAD

**Issue by eleogran** [iLCSoft/LCIO#11]
In order to identify hits produced by secondary, low energy, particles that are not kept in the MCParticle history records, it would be nice to have a BitField in the SimTrackerHits to store this information.

**Comment by dhynds** [comment]
I joined GitHub just to add a thumbs up icon??? Really?!

**Comment by gaede** [comment]
You'll need your Github account to maintain ConformalTracking, once it is moved - so good that you have one finally ;-)

**Comment by andresailer** [comment]
@gaede Will you add this field, or can you tell me what files I need to change to add the field?
Thanks

**Comment by andresailer** [comment]
Implemented in #21
