### ISSUE TITLE
delphes2lcio crash

### ISSUE THREAD

**Issue by danieljeans** [iLCSoft/LCIO#113]
I came across a crash of DelphesSTDHEP2LCIO, due to the use of
GetEntriesFast() in l.771 of DelphesLCIOConverter::convertJetCollection

This was an empty jet, for which GetEntries() gave 0 while GetEntriesFast() returned 1 (which lead to an invalid access shortly afterwards.) It's weird to me that they should give different answers...I haven't tried to understand why.
Changing to GetEntries() fixed the problem. (I see that the "Fast" version is also used in various other places.)

**Comment by rete** [comment]
@gaede Is this the recent issue you fixed?

**Comment by gaede** [comment]
I have fixed it, though I could not reproduce it. Anyways nothing wrong with the fix, I hope...

**Comment by danieljeans** [comment]
Thanks, I'd forgotten about this. I remember it affected just one event (but don't remember which one...). The fix looks fine.
