### ISSUE TITLE
parallel build does not seem to work if scio is not built quickly enough

### ISSUE THREAD

**Issue by joequant** [iLCSoft/LCIO#114]
there is a dependency that's missing with parallel builds.  libsio is not being built before lcio is being linked

 - OS version: e.g. SLC6

linux

 - Compiler version: e.g GCC 6.2
gcc10
 - Package version: tag, commit ID or GitHub branch
02-14-02
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment, cmake, build, run...
 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: A short description of what you are trying to achieve

**Comment by joequant** [comment]
[spack-build-out.txt](https://github.com/iLCSoft/LCIO/files/5248809/spack-build-out.txt)

**Comment by joequant** [comment]
Here is a patch that fixes this issue

 # lcio library
 ADD_SUBDIRECTORY( ./src/cpp lcio )
 
-
+IF( NOT SIO_FOUND )
+  ADD_DEPENDENCIES( lcio sio )
+ENDIF()

**Comment by andresailer** [comment]
This was fixed in https://github.com/iLCSoft/LCIO/pull/91. version 2.15 and onwards, they are not yet part of the spack recipe.

**Comment by andresailer** [comment]
Spack PR https://github.com/spack/spack/pull/18841
