### ISSUE TITLE
Getting 0 event for a run and  LCIORandomAccessMgr::getEventMap() recreating event map for direct access (old file) message

### ISSUE THREAD

**Issue by arturo-rodriguez35** [iLCSoft/LCIO#128]
- OS version: lxplus centos7
 - Compiler version: GCC 6.2
 - Package version: tag v02-15-04
 
Hi all,
I'm having problems running this simple script on a converted data from a test beam campaign.
```
from pyLCIO import IOIMPL
from ROOT import TCanvas, TH1D, vector

# create a reader and open an LCIO file
reader = IOIMPL.LCFactory.getInstance().createLCReader()
reader.open( 'run1688.slcio' )

print(reader.getNumberOfEvents())

```
I get the following message. 
```
Loading LCIO ROOT dictionaries ...
LCIORandomAccessMgr::getEventMap() recreating event map for direct access (old file)
0

```
However, the run should have more than 200k events. You can find the slcio file [here](https://cernbox.cern.ch/index.php/s/NjkcYmWtyeBN8VI). Can you point me to the possible causes of the problem?
I really appreciate any help you can provide.

**Comment by gaede** [comment]
The file is corrupted as it does not have the table-of-contents at the end which is needed for direct access and is used in
`reader.getNumberOfEvents()`.  Possibly the job that created the file has crashed (or missed to properly call `LCWriter::close()` at the end).  The data is still there and you should be able to read it sequentially with `LCReader::readNextEvent()`.  You can also run `$LCIO/bin/copyfix run1688.slcio run1688_fixed.slcio` to create a correct LCIO file with the appropriate TOC at the end.  Note that this is a bit slow, however.  
This should also happen automatically (and fast) with `LCIORandomAccessMgr::getEventMap() recreating event map for direct access (old file)` but this does not seem to work and might be a bug in LCIO...

**Comment by gaede** [comment]
@rete Something seems to have gone wrong with the new implementation of the `LCReader` can you please have a look.

**Comment by rete** [comment]
First investigations:

- I could reproduce the bug
- I tried the same with `lcio_event_counter`. Gives also 0. I conclude that this is not a python issue
- Switched ON the SIO debug by hand (I need to add a CMake switch in LCIO in a future PR...). No weird message so far, records are read one by one without error or even warnings.

I suspect something wrong in LCIO, not SIO itself. I will investigate more and come back to you.

**Comment by gaede** [comment]
Could be somewhere in the re-implementation of the SIOReader - possibly a missing fseek(0) when re-creating the table of contents ?
