### ISSUE TITLE
Tag release

### ISSUE THREAD

**Issue by jstrube** [iLCSoft/LCIO#18]
I see that versions.readme already mentions v02-07-05. Is this ready to be tagged on github?

**Comment by andresailer** [comment]
would be nice to get #11, and I guess #6 into this release as well.

**Comment by gaede** [comment]
We are preparing v02-08 which includes #11.  #6 will have to wait for a future release ( there does not seem to be a lot of pressure to have it asap.

**Comment by andresailer** [comment]
2.8 was released https://github.com/iLCSoft/LCIO/releases/tag/v02-08
