### ISSUE TITLE
more examples for LCIO - in Go

### ISSUE THREAD

**Issue by sbinet** [iLCSoft/LCIO#20]
hi there,

I see under the `examples` directory a few examples on how to read/write `LCIO` files from `Fortran`, `C++`, `Java` and `Python`:

https://github.com/iLCSoft/LCIO/tree/master/examples/python

would there be interest in an example showing the same but using [Go](https://golang.org)?

I have already the library for reading/writing `sio` files and some bits and pieces to read `LCRunHeader`:

- https://godoc.org/go-hep.org/x/hep/sio
- https://github.com/go-hep/hep/blob/master/sio/stream_test.go

(adding the remaining ones "should" be easy -- "famous last words")

let me know.

**Comment by gaede** [comment]
Hi Sebastien,
a Go binding for LCIO would clearly be nice to have. However the existing bindings for Java, Fortran and Python are complete wrt. to the LCIO EDM. So  a Go binding should also be complete, if we want to add it to LCIO itself. Not sure how much work this is and whether you want to invest in this ( could this be done with scripting ?). 
If you just have some examples of how a Go binding could look like, we could refer to it in the documentation. 
Cheers, Frank.

**Comment by gaede** [comment]
lcio.xml describes the actual layout of the LCIO data structure in the files and is thus fairly stable. We never remove things but occasionally added new attributes in the past (as you can see from the condition expressions referring to past LCIO versions). So the actual I/O could be generated from lcio.xml - the data classes themselves have additional convenient methods that would have to be implemented manually, in a second step.

**Comment by sbinet** [comment]
`master` go-hep/hep@f521be9 (tag=`v0.2`) has a decent r/w support for the following types:

- `MCParticle`
- `SimTrackerHit`
- `SimCalorimeterHit`
- `LCFloatVec`
- `LCIntVec`
- `LCStrVec`
- `RawCalorimeterHit`
- `CalorimeterHit`
- `TrackerHit`
- `TrackerHitPlane`
- `Track`
- `Cluster`
- `Vertex`
- `ReconstructedParticle`
- `LCGenericObject`

I have also added `LCReader` and `LCWriter` -like types to easily iterate over events:
https://github.com/go-hep/hep/blob/v0.2/lcio/writer_test.go#L113

the `dumpevent` like command now lives here:
https://github.com/go-hep/hep/blob/v0.2/lcio/cmd/lcio-ls/main.go

I'll prepare a little example beginning of next week.

**Comment by sbinet** [comment]
@gaede PTAL.
