### ISSUE TITLE
Missing cmake macros when using find_package() with LCIO

### ISSUE THREAD

**Issue by JeremyMcCormick** [iLCSoft/LCIO#28]
Hi,

In my build system, when I am using `find_package()` to locate LCIO, I get errors similar to these:

```
CMake Error at /home/chekanov/hepsim_osg/ilcsoft/fpadsim-1.5/lcio/LCIOConfigVersion.cmake:14 (INCLUDE):
 include could not find load file:

/home/chekanov/hepsim_osg/ilcsoft/fpadsim-1.5/lcio/cmake/MacroCheckPackageVersion.cmake
Call Stack (most recent call first):
 CMakeLists.txt:52 (FIND_PACKAGE)


CMake Error at /home/chekanov/hepsim_osg/ilcsoft/fpadsim-1.5/lcio/LCIOConfigVersion.cmake:15 (CHECK_PACKAGE_VERSION):
 Unknown CMake command "CHECK_PACKAGE_VERSION".
Call Stack (most recent call first):
 CMakeLists.txt:52 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/chekanov/hepsim_osg/ilcsoft/fpadsim-1.5/slic/master/build/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target `install'.  Stop.
```

I believe this is because the `LCIOConfig.cmake` and `LCIOConfigVersion.cmake` macros are referencing CMake macros which do not resolve correctly, namely:

```
INCLUDE( "${CMAKE_CURRENT_LIST_DIR}/cmake/MacroCheckPackageLibs.cmake" )
```

Since `CMAKE_CURRENT_LIST_DIR` is actually going to be set to the LCIO prefix dir when running `find_package()` (at least that appears to be the case in my build script), these cmake macros will not be found there as they are not installed by the LCIO build system.

It seems that this could be fixed by having LCIO install the scripts from the `cmake` dir into the installation dir.

It could be possible to work around this if these cmake macros were referenced by relative path by appending the source dir's `cmake` dir to `CMAKE_MODULE_PATH` but an absolute path is hard-coded here so that won't work.

For now, I work around it by providing my own `FindLCIO` macro but obviously I'd prefer to use the cmake files generated by LCIO if I can but they need to be "standalone" and not reference cmake macros which may not exist from where `find_package` is being run.

This is using the v02-07-04 tag of LCIO, so perhaps this is done differently in more recent versions.

**Comment by gaede** [comment]
This should have been fixed in v02-07-05. Please try this - or better the latest release v02-08.

**Comment by JeremyMcCormick** [comment]
Okay thanks, Frank....will give v02-07-05 a try then.
