### ISSUE TITLE
FindROOT.cmake should be removed

### ISSUE THREAD

**Issue by rete** [iLCSoft/LCIO#68]
ROOT provides a ROOTConfig.cmake. LCIO should not maintain a FindROOT.cmake with its own set of CMake variables. Moreover, here the meaning of ROOT_DIR is "path to ROOT installation" whereas for CMake it means "path to ROOTConfig.cmake".

TODO: 
- Remove FindROOT.cmake
- Adapt CMake files to handle variables from ROOTConfig.cmake

**Comment by gaede** [comment]
Please provide a corresponding PR.
