### ISSUE TITLE
Adaptation to new PyROOT

### ISSUE THREAD

**Issue by etejedor** [iLCSoft/LCIO#73]
Dear pyLCIO Maintainers,

I am the person responsible for the ROOT Python bindings (PyROOT) and I am writing this issue because the ROOT team has switched ROOT master to a new PyROOT, which will be first released in ROOT 6.22 (May 2020).

The new PyROOT has a few backward incompatible changes, the most important ones are explained here:

https://docs.google.com/presentation/d/1nv22_TSJsGyudrDvtFsxy5NL39S4gPXvJE4f3eeg3LI/edit?usp=sharing

I would like to bring your attention to one of them specifically, since I have seen that it is causing a test failure when importing pyLCIO in one of the LCG nightly tests that uses the dev3 stack (ROOT master):

http://cdash.cern.ch/testDetails.php?test=82225223&build=840256

The fix is easy, it should be enough not to use `MethodProxy`, but `CPPOverload` instead (it is just a name change).

So the code in `pyLCIO/base/HandleExceptions.py` should no longer do:
```python
import ROOT
...
        if isinstance(method, ROOT.MethodProxy):
```
but
```python
from libcppyy import CPPOverload
...
        if isinstance(method, CPPOverload):
```

If you detect any other issue, and you can't find the reason in the slides I mentioned above, please open a JIRA ticket here:
https://sft.its.cern.ch/jira/secure/CreateIssue.jspa?pid=10010&issuetype=1

Best,

Enric

**Comment by rete** [comment]
Hi Enric,
thanks for opening an issue!

We made recent changes into our iLCSoft stack recently to use ROOT 6.18.04. 

I have 2 questions for you then:
- Starting from which version of ROOT do we expect this change(s)?
- How to deal with backward compatibility? It is important for us that pyLCIO remains functional with recent and older versions of ROOT. 

Thanks a again for opening the issue.
Cheers, Remi

**Comment by etejedor** [comment]
Hi Remi,

Good to hear from you!

To answer your questions:
- The new PyROOT will become the default in 6.22, now it is only default in ROOT master. We would like to have this release in May 2020.

- Unfortunately, the new PyROOT has a few backwards incompatible changes, since it has been completely redesigned on top of the cppyy library (which offers the dynamic Python-C++ bindings). In ROOT 6.20 (already released) you can use the old PyROOT with a few forward compatible changes, explained here:

https://docs.google.com/presentation/d/1tWmtbsc3DBPolQYubdMmBBGSw4J_Tzaqto3kJKrhJbE/edit?usp=sharing

to start adapting your code.

Therefore I am afraid that some degree of adaptation will be necessary. I am of course at your disposal to help you with that. The first thing I would do is assess how much these backward compatible changes affect the code of pyLCIO. Apart from the problem I started this issue with, are there any others? Do they appear in the slides I shared?

I just wanted to say that this redesign of the new PyROOT is done for the best. It will bring more modern Python bindings, more Pythonic and with more features that integrate them with the Python ecosystem (e.g. numpy, pandas...). It will also fix a number of bugs present in the old PyROOT.

**Comment by petricm** [comment]
@gaede back to the discussion from the key4hep meeting
```py
In [1]: from ROOT import gROOT 
In [2]: gROOT.GetVersion()
Out[2]: '6.20/02'
```
